# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://liuxiong21.github.io
date_format: "ordinal"
title: CodeMinner
subtitle: "专注于Java底层及开源项目"
description: "刘雄的个人博客"
keywords: 代码旷工, Xiong Liu, CodeMinner
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Xiong Liu
organization: codeminner.com
organization_url: http://codeminner.com
github_username: liuxiong21
location: Shenzhen, China
email: liuxiong21@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: liuxiong21/liuxiong21.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: liuxiong21
    repo: blog-comments
    oauth:
        client_id: 8216f2a0a3ea9134af7a
        client_secret: 1c186cc0f68280040a8dd477e2de12dcf3756c8a
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: liuxiong21
    repo: blog-comments
    clientID: 8216f2a0a3ea9134af7a
    clientSecret: 1c186cc0f68280040a8dd477e2de12dcf3756c8a
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-33283596-1
